name: CI

on:
  - push
  - pull_request
  - workflow_call

jobs:
  lint:
    uses: adonisjs/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: adonisjs/.github/.github/workflows/typecheck.yml@main

  tests:
    uses: adonisjs/.github/.github/workflows/test.yml@main
